# Generated by Django 6.0 on 2025-12-19 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muiv_graduation_system', '0003_employer_alter_graduate_user_document_employment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Работодатель', 'verbose_name_plural': 'Работодатели'},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'verbose_name': 'Трудоустройство', 'verbose_name_plural': 'Трудоустройства'},
        ),
        migrations.AlterModelOptions(
            name='employmentstatus',
            options={'verbose_name': 'Статус трудоустройства', 'verbose_name_plural': 'Статусы трудоустройства'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
        migrations.AlterModelOptions(
            name='graduate',
            options={'verbose_name': 'Выпускник', 'verbose_name_plural': 'Выпускники'},
        ),
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': 'Заявка на регистрацию', 'verbose_name_plural': 'Заявки на регистрацию'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='document',
            name='filepath',
            field=models.CharField(max_length=500, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='document',
            name='graduate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='muiv_graduation_system.graduate', verbose_name='Выпускник'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muiv_graduation_system.employer', verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='graduate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='muiv_graduation_system.graduate', verbose_name='Выпускник'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muiv_graduation_system.employmentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Статус трудоустройства'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='graduation_year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Подтверждено пользователем'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='password_hash',
            field=models.CharField(max_length=128, verbose_name='Хеш пароля'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filepath',
            field=models.CharField(max_length=500, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='report',
            name='format',
            field=models.CharField(max_length=10, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название отчета'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muiv_graduation_system.role', verbose_name='Роль пользователя'),
        ),
    ]
